### ISSUE TITLE
Copying instead of moving in /tmp/ for glitching the same image 

### ISSUE THREAD

**Issue by klaa97** [xero/glitchlock#1]
In the paragraph where you explain how to use a preselected image instead of scrot, using mv would cause the same image to be glitched over and over resulting in not aesthetically good results (grey screen basically). I suggest you to change the `mv` to `cp` here.
> with a command to move your pre-setup screenshot into place (e.g. mv ~/lib/img/lock.png /tmp/lock.png) then let the script randomly glitch that image out everytime.

**Comment by xero** [comment]
ty for pointing this out. that's actually what i intended. :+1:
